/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author 181710059
 */
public class OrdemDeServiço extends javax.swing.JInternalFrame {

    /**
     * Creates new form OrdemDeServiço
     */
    public OrdemDeServiço() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labCADASTRO = new javax.swing.JLabel();
        labCODIGO = new javax.swing.JLabel();
        labNOME = new javax.swing.JLabel();
        labNome = new javax.swing.JLabel();
        labENDERECO = new javax.swing.JLabel();
        labCIDADE = new javax.swing.JLabel();
        labEQUIPAMENTO = new javax.swing.JLabel();
        labMARCAMODELO = new javax.swing.JLabel();
        labDEFEITO = new javax.swing.JLabel();
        labSERVICO = new javax.swing.JLabel();
        labVALOR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtareaDefeito = new javax.swing.JTextArea();
        labDESCONTO = new javax.swing.JLabel();
        labIMAIL = new javax.swing.JLabel();
        labTécnico = new javax.swing.JLabel();
        txtCADASTRO = new javax.swing.JTextField();
        txtCODIGO = new javax.swing.JTextField();
        txtNOME = new javax.swing.JTextField();
        txtIMAIL = new javax.swing.JTextField();
        txtTELEFONE = new javax.swing.JTextField();
        txtENDERECO = new javax.swing.JTextField();
        txtCIDADE = new javax.swing.JTextField();
        txtEQUIPAMENTO = new javax.swing.JTextField();
        txtMARCAMODELO = new javax.swing.JTextField();
        txtSERVICO = new javax.swing.JTextField();
        txtVALOR = new javax.swing.JTextField();
        txtDESCONTO = new javax.swing.JTextField();
        txtTECNICO = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ordem de serviço");

        labCADASTRO.setText("Cadastro");

        labCODIGO.setText("Codigo");

        labNOME.setText("Nome");

        labNome.setText("Telefone");

        labENDERECO.setText("Endereço");

        labCIDADE.setText("Cidade");

        labEQUIPAMENTO.setText("Equipamento");

        labMARCAMODELO.setText("Marca e Modelo");

        labDEFEITO.setText("Defeito");

        labSERVICO.setText("Serviço");

        labVALOR.setText("Valor");

        txtareaDefeito.setColumns(20);
        txtareaDefeito.setRows(5);
        txtareaDefeito.setText("Descreva aqui o defeito\n");
        jScrollPane1.setViewportView(txtareaDefeito);

        labDESCONTO.setText("Desconto");

        labIMAIL.setText("Imail");

        labTécnico.setText("Técnico");

        txtCADASTRO.setText("000000000000");

        txtCODIGO.setText("000000000000");

        txtTELEFONE.setText("00 000000000");

        txtVALOR.setText("R$");

        txtDESCONTO.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labTécnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTECNICO))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labMARCAMODELO)
                        .addGap(18, 18, 18)
                        .addComponent(txtMARCAMODELO))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labEQUIPAMENTO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEQUIPAMENTO))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labCIDADE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCIDADE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labENDERECO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtENDERECO))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labCADASTRO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labDEFEITO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labDESCONTO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDESCONTO, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labNOME)
                        .addGap(18, 18, 18)
                        .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labCODIGO)
                        .addGap(18, 18, 18)
                        .addComponent(txtCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labIMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labVALOR, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labSERVICO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVALOR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSERVICO, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCADASTRO)
                    .addComponent(txtCADASTRO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCODIGO)
                    .addComponent(txtCODIGO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNOME)
                    .addComponent(txtNOME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labIMAIL)
                    .addComponent(txtIMAIL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labNome)
                    .addComponent(txtTELEFONE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labENDERECO)
                    .addComponent(txtENDERECO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labCIDADE)
                    .addComponent(txtCIDADE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labEQUIPAMENTO)
                    .addComponent(txtEQUIPAMENTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labMARCAMODELO)
                    .addComponent(txtMARCAMODELO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labDEFEITO))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labSERVICO)
                    .addComponent(txtSERVICO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labVALOR)
                    .addComponent(txtVALOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labDESCONTO)
                    .addComponent(txtDESCONTO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labTécnico)
                    .addComponent(txtTECNICO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labCADASTRO;
    private javax.swing.JLabel labCIDADE;
    private javax.swing.JLabel labCODIGO;
    private javax.swing.JLabel labDEFEITO;
    private javax.swing.JLabel labDESCONTO;
    private javax.swing.JLabel labENDERECO;
    private javax.swing.JLabel labEQUIPAMENTO;
    private javax.swing.JLabel labIMAIL;
    private javax.swing.JLabel labMARCAMODELO;
    private javax.swing.JLabel labNOME;
    private javax.swing.JLabel labNome;
    private javax.swing.JLabel labSERVICO;
    private javax.swing.JLabel labTécnico;
    private javax.swing.JLabel labVALOR;
    private javax.swing.JTextField txtCADASTRO;
    private javax.swing.JTextField txtCIDADE;
    private javax.swing.JTextField txtCODIGO;
    private javax.swing.JTextField txtDESCONTO;
    private javax.swing.JTextField txtENDERECO;
    private javax.swing.JTextField txtEQUIPAMENTO;
    private javax.swing.JTextField txtIMAIL;
    private javax.swing.JTextField txtMARCAMODELO;
    private javax.swing.JTextField txtNOME;
    private javax.swing.JTextField txtSERVICO;
    private javax.swing.JTextField txtTECNICO;
    private javax.swing.JTextField txtTELEFONE;
    private javax.swing.JTextField txtVALOR;
    private javax.swing.JTextArea txtareaDefeito;
    // End of variables declaration//GEN-END:variables
}
